# Generated by Django 5.0.4 on 2024-04-10 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "0018_improve_crontab_helptext"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ScanDescriptor",
            new_name="ScanAutoSubmitter",
        ),
    ]
