# Generated by Django 5.0.4 on 2024-04-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domainscan",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("success", "Success"),
                    ("error", "Error"),
                ],
                db_index=True,
                default="pending",
                max_length=32,
            ),
        ),
    ]
