# Generated by Django 5.0.4 on 2024-04-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_rename_scandescriptor_scanautosubmitter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discovereddomain",
            name="seed",
        ),
        migrations.AddField(
            model_name="discovereddomain",
            name="seeds",
            field=models.ManyToManyField(
                related_name="discovered", to="inventory.seeddomain"
            ),
        ),
    ]
