# Generated by Django 5.0.4 on 2024-04-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_remove_discovereddomain_seed_discovereddomain_seeds"),
    ]

    operations = [
        migrations.AddField(
            model_name="seeddomain",
            name="enabled",
            field=models.PositiveIntegerField(default=True),
        ),
    ]
