# Generated by Django 5.0.4 on 2024-04-11 05:19

import datetime
import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_celery_beat", "0018_improve_crontab_helptext"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "filter_type",
                    models.CharField(
                        choices=[
                            ("value__startswith", "Starts with"),
                            ("value__endswith", "Ends with"),
                            ("value__contains", "Contains"),
                        ],
                        max_length=32,
                    ),
                ),
                ("filter_value", models.CharField()),
                (
                    "last_executed",
                    models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
                ),
                ("api_id", models.BigIntegerField()),
                ("api_hash", models.CharField(max_length=1024)),
                ("chat_id", models.BigIntegerField()),
                (
                    "interval",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_celery_beat.intervalschedule",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WebHookReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "filter_type",
                    models.CharField(
                        choices=[
                            ("value__startswith", "Starts with"),
                            ("value__endswith", "Ends with"),
                            ("value__contains", "Contains"),
                        ],
                        max_length=32,
                    ),
                ),
                ("filter_value", models.CharField()),
                (
                    "last_executed",
                    models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
                ),
                ("url", models.URLField()),
                ("message_param", models.CharField(default="content")),
                ("file_param", models.CharField(default="file")),
                (
                    "interval",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_celery_beat.intervalschedule",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
