# Generated by Django 5.0.4 on 2024-04-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0002_remove_telegramreport_creds_telegramreport_api_hash_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramreport",
            name="api_id",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="telegramreport",
            name="chat_id",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="telegramreport",
            name="filter",
            field=models.CharField(
                default="%", help_text="Filter will be applied in a like clause"
            ),
        ),
    ]
