# Generated by Django 5.0.4 on 2024-04-10 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "0018_improve_crontab_helptext"),
        ("report", "0004_telegramreport_enabled_telegramreport_interval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramreport",
            name="interval",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="django_celery_beat.intervalschedule",
            ),
        ),
    ]
