# Generated by Django 5.0.4 on 2024-04-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0005_alter_telegramreport_interval"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramreport",
            name="last_executed",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
