# Generated by Django 5.0.4 on 2024-04-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0007_alter_telegramreport_last_executed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telegramreport",
            name="filter",
        ),
        migrations.AddField(
            model_name="telegramreport",
            name="filter_type",
            field=models.IntegerField(
                choices=[(1, "Starts with"), (2, "Ends with"), (3, "Contains")],
                default=1,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="telegramreport",
            name="filter_value",
            field=models.CharField(default="dd"),
            preserve_default=False,
        ),
    ]
