# Generated by Django 5.0.4 on 2024-04-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0008_remove_telegramreport_filter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramreport",
            name="filter_type",
            field=models.IntegerField(
                choices=[
                    ("value__startswith", "Starts with"),
                    ("value__endswith", "Ends with"),
                    ("value__contains", "Contains"),
                ]
            ),
        ),
    ]
