# Generated by Django 5.0.4 on 2024-04-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0009_alter_telegramreport_filter_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramreport",
            name="filter_type",
            field=models.CharField(
                choices=[
                    ("value__startswith", "Starts with"),
                    ("value__endswith", "Ends with"),
                    ("value__contains", "Contains"),
                ],
                max_length=32,
            ),
        ),
    ]
