# Generated by Django 5.0.4 on 2024-04-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0011_webhookreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookreport",
            name="file_param",
            field=models.CharField(default="file"),
        ),
        migrations.AddField(
            model_name="webhookreport",
            name="message_param",
            field=models.CharField(default="message"),
        ),
    ]
